# Generated by Django 4.2.14 on 2024-07-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
